"""Celery task names (C-JOBS contract ids)."""

TRIGGER_DRAIN = "prodavan.jobs.trigger_drain"
DISPATCH_TRIGGER = "prodavan.jobs.dispatch_trigger"
IDLE_PAUSE_SWEEP = "prodavan.jobs.idle_pause_sweep"
REMATERIALIZE_PROJECT = "prodavan.jobs.rematerialize_project"
WIPE_CABINET_PACKAGES = "prodavan.jobs.wipe_cabinet_packages"
WIPE_PROJECT_TREE = "prodavan.jobs.wipe_project_tree"
GC_ORPHAN_CABINET_SCHEMAS = "prodavan.jobs.gc_orphan_cabinet_schemas"
GC_ORPHAN_BLOBS = "prodavan.jobs.gc_orphan_blobs"
APPLY_AUTH_USER_REGISTERED = "prodavan.jobs.apply_auth_user_registered"
CASCADE_COMPANY_DELETED = "prodavan.jobs.cascade_company_deleted"
POD_RECONCILE = "prodavan.jobs.pod_reconcile"
INDEX_EQUIPMENT_CATALOG = "prodavan.jobs.index_equipment_catalog"
SWEEP_EQUIPMENT_CATALOG_REINDEX = "prodavan.jobs.sweep_equipment_catalog_reindex"
AGENT_RUN_STALL_SWEEP = "prodavan.jobs.agent_run_stall_sweep"
