apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis.yaml
  - minio.yaml
  - mongodb.yaml
  - opensearch.yaml
  - kafka.yaml
  - celery.yaml
  - keycloak.yaml
  - searxng.yaml
  - gotenberg.yaml
  - pdb.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: agentscale-kafka-config
    files:
      - redpanda.yaml
  - name: agentscale-minio-api-policy
    files:
      - minio-api-policy.json
  - name: agentscale-keycloak-realm
    files:
      - realm-agentscale.json
