"""Tenant Infra Cache port."""

from __future__ import annotations

from typing import Protocol


class TenantCachePort(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, *, ttl_sec: int | None) -> bool: ...

    async def delete(self, key: str) -> bool: ...

    async def incr(self, key: str, *, amount: int = 1, ttl_sec: int | None = None) -> int | None: ...

    async def index_add(self, index_key: str, member: str) -> int: ...

    async def index_remove(self, index_key: str, member: str) -> None: ...

    async def index_card(self, index_key: str) -> int: ...

    async def index_members(self, index_key: str) -> list[str]: ...

    async def purge_keys(self, keys: list[str]) -> int: ...
