apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodavan-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ne-tort/prodavan.git
    targetRevision: main
    path: infra/k3s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: prodavan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
