apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentscale-api-storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
