apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - rbac-sandboxes.yaml
  - hydrate-secret.yaml
  - pod-agent-bridge-auth-secret.yaml
  - probe-pod.yaml
