apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prodavan-sandboxes
resources:
  - sandboxtemplate.yaml
  - sandboxwarmpool.yaml
  - rbac-sandboxes.yaml
  - networkpolicy.yaml
